### PR TITLE
Filter non serializable properties before saving state

### PR DESCRIPTION
**Pull request by andrefgneves**

### CODE REVIEW

**Comment by gregorypratt** [comment]
The router should wait for the `resolve` method to complete before moving onto the state. https://github.com/RiotGear/rg-router#add

This works when you go to state or refresh the page, but it doesn't when the back button is used since its removed from state on save.

**Comment by andrefgneves** [comment]
Ops, sorry about that. I did that change in a hurry and couldn't properly test it.
It believe it will work fine now.

Can you please check again?

**Comment by gregorypratt** [comment]
Right cool, I've manually merged and updated the code ;-)

Thank you so much for your time on this!

**Comment by gregorypratt** [comment]
If you're happy I'll publish v1.3.0 to NPM :+1:

**Comment by andrefgneves** [comment]
My pleasure :)
Yes, please do.

**Pull request closed without merging**
